package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Activitate generated by hbm2java
 */
@Entity
@Table(name = "activitate", catalog = "MedicalEcoSystem")
public class Activitate implements java.io.Serializable {

	private Integer id;
	private Disciplina disciplina;
	private Utilizatori utilizatori;
	private String tip;
	private Set orars = new HashSet(0);

	public Activitate() {
	}

	public Activitate(Disciplina disciplina, Utilizatori utilizatori, String tip) {
		this.disciplina = disciplina;
		this.utilizatori = utilizatori;
		this.tip = tip;
	}

	public Activitate(Disciplina disciplina, Utilizatori utilizatori, String tip, Set orars) {
		this.disciplina = disciplina;
		this.utilizatori = utilizatori;
		this.tip = tip;
		this.orars = orars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_disciplina", nullable = false)
	public Disciplina getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cnp_cadru_didactic", nullable = false)
	public Utilizatori getUtilizatori() {
		return this.utilizatori;
	}

	public void setUtilizatori(Utilizatori utilizatori) {
		this.utilizatori = utilizatori;
	}

	@Column(name = "tip", nullable = false, length = 9)
	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activitate")
	public Set getOrars() {
		return this.orars;
	}

	public void setOrars(Set orars) {
		this.orars = orars;
	}

}
