package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Catalog generated by hbm2java
 */
@Entity
@Table(name = "catalog", catalog = "MedicalEcoSystem")
public class Catalog implements java.io.Serializable {

	private CatalogId id;
	private Disciplina disciplina;
	private Utilizatori utilizatori;
	private int nota;
	private Date data;

	public Catalog() {
	}

	public Catalog(CatalogId id, Disciplina disciplina, Utilizatori utilizatori, int nota, Date data) {
		this.id = id;
		this.disciplina = disciplina;
		this.utilizatori = utilizatori;
		this.nota = nota;
		this.data = data;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cnpStudent", column = @Column(name = "cnp_student", nullable = false, length = 13)),
			@AttributeOverride(name = "codDisciplina", column = @Column(name = "cod_disciplina", nullable = false)) })
	public CatalogId getId() {
		return this.id;
	}

	public void setId(CatalogId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_disciplina", nullable = false, insertable = false, updatable = false)
	public Disciplina getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cnp_student", nullable = false, insertable = false, updatable = false)
	public Utilizatori getUtilizatori() {
		return this.utilizatori;
	}

	public void setUtilizatori(Utilizatori utilizatori) {
		this.utilizatori = utilizatori;
	}

	@Column(name = "nota", nullable = false)
	public int getNota() {
		return this.nota;
	}

	public void setNota(int nota) {
		this.nota = nota;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
