package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatalogId generated by hbm2java
 */
@Embeddable
public class CatalogId implements java.io.Serializable {

	private String cnpStudent;
	private int codDisciplina;

	public CatalogId() {
	}

	public CatalogId(String cnpStudent, int codDisciplina) {
		this.cnpStudent = cnpStudent;
		this.codDisciplina = codDisciplina;
	}

	@Column(name = "cnp_student", nullable = false, length = 13)
	public String getCnpStudent() {
		return this.cnpStudent;
	}

	public void setCnpStudent(String cnpStudent) {
		this.cnpStudent = cnpStudent;
	}

	@Column(name = "cod_disciplina", nullable = false)
	public int getCodDisciplina() {
		return this.codDisciplina;
	}

	public void setCodDisciplina(int codDisciplina) {
		this.codDisciplina = codDisciplina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatalogId))
			return false;
		CatalogId castOther = (CatalogId) other;

		return ((this.getCnpStudent() == castOther.getCnpStudent()) || (this.getCnpStudent() != null
				&& castOther.getCnpStudent() != null && this.getCnpStudent().equals(castOther.getCnpStudent())))
				&& (this.getCodDisciplina() == castOther.getCodDisciplina());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCnpStudent() == null ? 0 : this.getCnpStudent().hashCode());
		result = 37 * result + this.getCodDisciplina();
		return result;
	}

}
