package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Channeling generated by hbm2java
 */
@Entity
@Table(name = "Channeling", catalog = "MedicalEcoSystem")
public class Channeling implements java.io.Serializable {

	private Integer idchanneling;
	private String enterBy;
	private Date issueDate;
	private String doctorName;
	private String speciality;
	private String channelData;
	private String channelTime;
	private String patientName;
	private String tpno;
	private String guardian;
	private String amount;
	private int idUser;

	public Channeling() {
	}

	public Channeling(int idUser) {
		this.idUser = idUser;
	}

	public Channeling(String enterBy, Date issueDate, String doctorName, String speciality, String channelData,
			String channelTime, String patientName, String tpno, String guardian, String amount, int idUser) {
		this.enterBy = enterBy;
		this.issueDate = issueDate;
		this.doctorName = doctorName;
		this.speciality = speciality;
		this.channelData = channelData;
		this.channelTime = channelTime;
		this.patientName = patientName;
		this.tpno = tpno;
		this.guardian = guardian;
		this.amount = amount;
		this.idUser = idUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idchanneling", unique = true, nullable = false)
	public Integer getIdchanneling() {
		return this.idchanneling;
	}

	public void setIdchanneling(Integer idchanneling) {
		this.idchanneling = idchanneling;
	}

	@Column(name = "enterBy", length = 45)
	public String getEnterBy() {
		return this.enterBy;
	}

	public void setEnterBy(String enterBy) {
		this.enterBy = enterBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "issueDate", length = 19)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "doctorName", length = 45)
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "speciality", length = 45)
	public String getSpeciality() {
		return this.speciality;
	}

	public void setSpeciality(String speciality) {
		this.speciality = speciality;
	}

	@Column(name = "channelData", length = 45)
	public String getChannelData() {
		return this.channelData;
	}

	public void setChannelData(String channelData) {
		this.channelData = channelData;
	}

	@Column(name = "channelTime", length = 45)
	public String getChannelTime() {
		return this.channelTime;
	}

	public void setChannelTime(String channelTime) {
		this.channelTime = channelTime;
	}

	@Column(name = "patientName", length = 45)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "tpno", length = 45)
	public String getTpno() {
		return this.tpno;
	}

	public void setTpno(String tpno) {
		this.tpno = tpno;
	}

	@Column(name = "guardian", length = 45)
	public String getGuardian() {
		return this.guardian;
	}

	public void setGuardian(String guardian) {
		this.guardian = guardian;
	}

	@Column(name = "amount", length = 45)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

}
