package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "City", catalog = "MedicalEcoSystem")
public class City implements java.io.Serializable {

	private Integer idCity;
	private String city;

	public City() {
	}

	public City(String city) {
		this.city = city;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCity", unique = true, nullable = false)
	public Integer getIdCity() {
		return this.idCity;
	}

	public void setIdCity(Integer idCity) {
		this.idCity = idCity;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
