package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compound generated by hbm2java
 */
@Entity
@Table(name = "Compound", catalog = "MedicalEcoSystem")
public class Compound implements java.io.Serializable {

	private Integer idCompound;
	private String name;
	private String description;
	private String molecularFormula;
	private String molecularStructure;
	private int idCompoundCatalog;
	private String molecularWeight;
	private Date assignDate;

	public Compound() {
	}

	public Compound(int idCompoundCatalog) {
		this.idCompoundCatalog = idCompoundCatalog;
	}

	public Compound(String name, String description, String molecularFormula, String molecularStructure,
			int idCompoundCatalog, String molecularWeight, Date assignDate) {
		this.name = name;
		this.description = description;
		this.molecularFormula = molecularFormula;
		this.molecularStructure = molecularStructure;
		this.idCompoundCatalog = idCompoundCatalog;
		this.molecularWeight = molecularWeight;
		this.assignDate = assignDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCompound", unique = true, nullable = false)
	public Integer getIdCompound() {
		return this.idCompound;
	}

	public void setIdCompound(Integer idCompound) {
		this.idCompound = idCompound;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "molecularFormula", length = 45)
	public String getMolecularFormula() {
		return this.molecularFormula;
	}

	public void setMolecularFormula(String molecularFormula) {
		this.molecularFormula = molecularFormula;
	}

	@Column(name = "molecularStructure", length = 45)
	public String getMolecularStructure() {
		return this.molecularStructure;
	}

	public void setMolecularStructure(String molecularStructure) {
		this.molecularStructure = molecularStructure;
	}

	@Column(name = "idCompoundCatalog", nullable = false)
	public int getIdCompoundCatalog() {
		return this.idCompoundCatalog;
	}

	public void setIdCompoundCatalog(int idCompoundCatalog) {
		this.idCompoundCatalog = idCompoundCatalog;
	}

	@Column(name = "MolecularWeight", length = 45)
	public String getMolecularWeight() {
		return this.molecularWeight;
	}

	public void setMolecularWeight(String molecularWeight) {
		this.molecularWeight = molecularWeight;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AssignDate", length = 10)
	public Date getAssignDate() {
		return this.assignDate;
	}

	public void setAssignDate(Date assignDate) {
		this.assignDate = assignDate;
	}

	@Override
	public String toString() {
		return "Compound [idCompound=" + idCompound + ", name=" + name + ", description=" + description
				+ ", molecularFormula=" + molecularFormula + ", molecularStructure=" + molecularStructure
				+ ", idCompoundCatalog=" + idCompoundCatalog + ", molecularWeight=" + molecularWeight + ", assignDate="
				+ assignDate + "]";
	}
	
	

}
