package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Disciplina generated by hbm2java
 */
@Entity
@Table(name = "disciplina", catalog = "MedicalEcoSystem")
public class Disciplina implements java.io.Serializable {

	private Integer cod;
	private String denumire;
	private String tip;
	private int nrOre;
	private int puncteCredit;
	private String examinare;
	private int anStudiu;
	private int semestru;
	private int grup;
	private Set examens = new HashSet(0);
	private Set optiuniContracts = new HashSet(0);
	private Set catalogs = new HashSet(0);
	private Set activitates = new HashSet(0);

	public Disciplina() {
	}

	public Disciplina(String denumire, String tip, int nrOre, int puncteCredit, String examinare, int anStudiu,
			int semestru, int grup) {
		this.denumire = denumire;
		this.tip = tip;
		this.nrOre = nrOre;
		this.puncteCredit = puncteCredit;
		this.examinare = examinare;
		this.anStudiu = anStudiu;
		this.semestru = semestru;
		this.grup = grup;
	}

	public Disciplina(String denumire, String tip, int nrOre, int puncteCredit, String examinare, int anStudiu,
			int semestru, int grup, Set examens, Set optiuniContracts, Set catalogs, Set activitates) {
		this.denumire = denumire;
		this.tip = tip;
		this.nrOre = nrOre;
		this.puncteCredit = puncteCredit;
		this.examinare = examinare;
		this.anStudiu = anStudiu;
		this.semestru = semestru;
		this.grup = grup;
		this.examens = examens;
		this.optiuniContracts = optiuniContracts;
		this.catalogs = catalogs;
		this.activitates = activitates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cod", unique = true, nullable = false)
	public Integer getCod() {
		return this.cod;
	}

	public void setCod(Integer cod) {
		this.cod = cod;
	}

	@Column(name = "denumire", nullable = false, length = 45)
	public String getDenumire() {
		return this.denumire;
	}

	public void setDenumire(String denumire) {
		this.denumire = denumire;
	}

	@Column(name = "tip", nullable = false, length = 15)
	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	@Column(name = "nr_ore", nullable = false)
	public int getNrOre() {
		return this.nrOre;
	}

	public void setNrOre(int nrOre) {
		this.nrOre = nrOre;
	}

	@Column(name = "puncte_credit", nullable = false)
	public int getPuncteCredit() {
		return this.puncteCredit;
	}

	public void setPuncteCredit(int puncteCredit) {
		this.puncteCredit = puncteCredit;
	}

	@Column(name = "examinare", nullable = false, length = 15)
	public String getExaminare() {
		return this.examinare;
	}

	public void setExaminare(String examinare) {
		this.examinare = examinare;
	}

	@Column(name = "an_studiu", nullable = false)
	public int getAnStudiu() {
		return this.anStudiu;
	}

	public void setAnStudiu(int anStudiu) {
		this.anStudiu = anStudiu;
	}

	@Column(name = "semestru", nullable = false)
	public int getSemestru() {
		return this.semestru;
	}

	public void setSemestru(int semestru) {
		this.semestru = semestru;
	}

	@Column(name = "grup", nullable = false)
	public int getGrup() {
		return this.grup;
	}

	public void setGrup(int grup) {
		this.grup = grup;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "disciplina")
	public Set getExamens() {
		return this.examens;
	}

	public void setExamens(Set examens) {
		this.examens = examens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "disciplina")
	public Set getOptiuniContracts() {
		return this.optiuniContracts;
	}

	public void setOptiuniContracts(Set optiuniContracts) {
		this.optiuniContracts = optiuniContracts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "disciplina")
	public Set getCatalogs() {
		return this.catalogs;
	}

	public void setCatalogs(Set catalogs) {
		this.catalogs = catalogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "disciplina")
	public Set getActivitates() {
		return this.activitates;
	}

	public void setActivitates(Set activitates) {
		this.activitates = activitates;
	}

}
