package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DoctorsDepartments generated by hbm2java
 */
@Entity
@Table(name = "doctors_departments", catalog = "MedicalEcoSystem")
public class DoctorsDepartments implements java.io.Serializable {

	private Integer idDepartment;
	private int departmentId;
	private String departmentName;

	public DoctorsDepartments() {
	}

	public DoctorsDepartments(int departmentId, String departmentName) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDepartment", unique = true, nullable = false)
	public Integer getIdDepartment() {
		return this.idDepartment;
	}

	public void setIdDepartment(Integer idDepartment) {
		this.idDepartment = idDepartment;
	}

	@Column(name = "department_id", nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "department_name", nullable = false, length = 30)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

}
