package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DoctorMes generated by hbm2java
 */
@Entity
@Table(name = "doctorMES", catalog = "MedicalEcoSystem")
public class DoctorMes implements java.io.Serializable {

	private String doctorsId;
	private String doctorsFirstName;
	private String doctorsLastName;
	private int departmentId;
	private String designation;
	private String bloodGroup;
	private String gender;
	private String email;
	private String academicQualification;
	private String specialization;
	private String phoneNumber;
	private String idNumber;
	private Date registrationDate;
	private String city;
	private String state;
	private String nationality;
	private String postalCode;
	private String kraPin;
	private Date dateOfBirth;

	public DoctorMes() {
	}

	public DoctorMes(String doctorsId, String doctorsFirstName, String doctorsLastName, int departmentId,
			String designation, String bloodGroup, String gender, String email, String academicQualification,
			String specialization, String phoneNumber, String idNumber, Date registrationDate, String city,
			String state, String nationality, String postalCode, String kraPin, Date dateOfBirth) {
		this.doctorsId = doctorsId;
		this.doctorsFirstName = doctorsFirstName;
		this.doctorsLastName = doctorsLastName;
		this.departmentId = departmentId;
		this.designation = designation;
		this.bloodGroup = bloodGroup;
		this.gender = gender;
		this.email = email;
		this.academicQualification = academicQualification;
		this.specialization = specialization;
		this.phoneNumber = phoneNumber;
		this.idNumber = idNumber;
		this.registrationDate = registrationDate;
		this.city = city;
		this.state = state;
		this.nationality = nationality;
		this.postalCode = postalCode;
		this.kraPin = kraPin;
		this.dateOfBirth = dateOfBirth;
	}

	@Id

	@Column(name = "doctors_id", unique = true, nullable = false, length = 11)
	public String getDoctorsId() {
		return this.doctorsId;
	}

	public void setDoctorsId(String doctorsId) {
		this.doctorsId = doctorsId;
	}

	@Column(name = "doctors_first_name", nullable = false, length = 20)
	public String getDoctorsFirstName() {
		return this.doctorsFirstName;
	}

	public void setDoctorsFirstName(String doctorsFirstName) {
		this.doctorsFirstName = doctorsFirstName;
	}

	@Column(name = "doctors_last_name", nullable = false, length = 20)
	public String getDoctorsLastName() {
		return this.doctorsLastName;
	}

	public void setDoctorsLastName(String doctorsLastName) {
		this.doctorsLastName = doctorsLastName;
	}

	@Column(name = "department_id", nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "designation", nullable = false, length = 20)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "blood_group", nullable = false, length = 3)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name = "gender", nullable = false, length = 6)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "email", nullable = false, length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "academic_qualification", nullable = false, length = 65535)
	public String getAcademicQualification() {
		return this.academicQualification;
	}

	public void setAcademicQualification(String academicQualification) {
		this.academicQualification = academicQualification;
	}

	@Column(name = "specialization", nullable = false, length = 20)
	public String getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(String specialization) {
		this.specialization = specialization;
	}

	@Column(name = "phone_number", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "id_number", nullable = false, length = 20)
	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registration_date", nullable = false, length = 19)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "city", nullable = false, length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "nationality", nullable = false, length = 30)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "postal_code", nullable = false, length = 30)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "kra_pin", nullable = false, length = 30)
	public String getKraPin() {
		return this.kraPin;
	}

	public void setKraPin(String kraPin) {
		this.kraPin = kraPin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", nullable = false, length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

}
