package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "Doctor", catalog = "MedicalEcoSystem")
public class Doctor implements java.io.Serializable {

	private int idUser;
	private int idSpeciality;

	public Doctor() {
	}

	public Doctor(int idUser, int idSpeciality) {
		this.idUser = idUser;
		this.idSpeciality = idSpeciality;
	}

	@Id

	@Column(name = "idUser", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "idSpeciality", nullable = false)
	public int getIdSpeciality() {
		return this.idSpeciality;
	}

	public void setIdSpeciality(int idSpeciality) {
		this.idSpeciality = idSpeciality;
	}

}
