package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DrugPharmacytrans generated by hbm2java
 */
@Entity
@Table(name = "Drug_Pharmacytrans", catalog = "MedicalEcoSystem")
public class DrugPharmacytrans implements java.io.Serializable {

	private DrugPharmacytransId id;

	public DrugPharmacytrans() {
	}

	public DrugPharmacytrans(DrugPharmacytransId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "drugIdDrug", column = @Column(name = "Drug_idDrug", nullable = false)),
			@AttributeOverride(name = "pharmacytransIdPharmacytrans", column = @Column(name = "Pharmacytrans_idPharmacytrans", nullable = false)) })
	public DrugPharmacytransId getId() {
		return this.id;
	}

	public void setId(DrugPharmacytransId id) {
		this.id = id;
	}

}
