package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Druggist generated by hbm2java
 */
@Entity
@Table(name = "Druggist", catalog = "MedicalEcoSystem")
public class Druggist implements java.io.Serializable {

	private Integer pkUser;
	private Integer fkUser;

	public Druggist() {
	}

	public Druggist(Integer fkUser) {
		this.fkUser = fkUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pkUser", unique = true, nullable = false)
	public Integer getPkUser() {
		return this.pkUser;
	}

	public void setPkUser(Integer pkUser) {
		this.pkUser = pkUser;
	}

	@Column(name = "fkUser")
	public Integer getFkUser() {
		return this.fkUser;
	}

	public void setFkUser(Integer fkUser) {
		this.fkUser = fkUser;
	}

}
