package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Enterprise generated by hbm2java
 */
@Entity
@Table(name = "Enterprise", catalog = "MedicalEcoSystem")
public class Enterprise implements java.io.Serializable {

	private Integer idEnterprise;
	private String name;
	private String type;
	private int idCity;

	public Enterprise() {
	}

	public Enterprise(String name, String type, int idCity) {
		this.name = name;
		this.type = type;
		this.idCity = idCity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEnterprise", unique = true, nullable = false)
	public Integer getIdEnterprise() {
		return this.idEnterprise;
	}

	public void setIdEnterprise(Integer idEnterprise) {
		this.idEnterprise = idEnterprise;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 18)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "idCity", nullable = false)
	public int getIdCity() {
		return this.idCity;
	}

	public void setIdCity(int idCity) {
		this.idCity = idCity;
	}

}
