package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name = "examen", catalog = "MedicalEcoSystem")
public class Examen implements java.io.Serializable {

	private ExamenId id;
	private Disciplina disciplina;
	private Date data;
	private int ora;
	private String sala;

	public Examen() {
	}

	public Examen(ExamenId id, Disciplina disciplina, Date data, int ora, String sala) {
		this.id = id;
		this.disciplina = disciplina;
		this.data = data;
		this.ora = ora;
		this.sala = sala;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codDisciplina", column = @Column(name = "cod_disciplina", nullable = false)),
			@AttributeOverride(name = "grupa", column = @Column(name = "grupa", nullable = false, length = 6)) })
	public ExamenId getId() {
		return this.id;
	}

	public void setId(ExamenId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_disciplina", nullable = false, insertable = false, updatable = false)
	public Disciplina getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "ora", nullable = false)
	public int getOra() {
		return this.ora;
	}

	public void setOra(int ora) {
		this.ora = ora;
	}

	@Column(name = "sala", nullable = false, length = 10)
	public String getSala() {
		return this.sala;
	}

	public void setSala(String sala) {
		this.sala = sala;
	}

}
