package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExamenId generated by hbm2java
 */
@Embeddable
public class ExamenId implements java.io.Serializable {

	private int codDisciplina;
	private String grupa;

	public ExamenId() {
	}

	public ExamenId(int codDisciplina, String grupa) {
		this.codDisciplina = codDisciplina;
		this.grupa = grupa;
	}

	@Column(name = "cod_disciplina", nullable = false)
	public int getCodDisciplina() {
		return this.codDisciplina;
	}

	public void setCodDisciplina(int codDisciplina) {
		this.codDisciplina = codDisciplina;
	}

	@Column(name = "grupa", nullable = false, length = 6)
	public String getGrupa() {
		return this.grupa;
	}

	public void setGrupa(String grupa) {
		this.grupa = grupa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExamenId))
			return false;
		ExamenId castOther = (ExamenId) other;

		return (this.getCodDisciplina() == castOther.getCodDisciplina())
				&& ((this.getGrupa() == castOther.getGrupa()) || (this.getGrupa() != null
						&& castOther.getGrupa() != null && this.getGrupa().equals(castOther.getGrupa())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodDisciplina();
		result = 37 * result + (getGrupa() == null ? 0 : this.getGrupa().hashCode());
		return result;
	}

}
