package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mesaje generated by hbm2java
 */
@Entity
@Table(name = "mesaje", catalog = "MedicalEcoSystem")
public class Mesaje implements java.io.Serializable {

	private Integer id;
	private String cnpSursa;
	private String cnpDestinatie;
	private String mesaj;
	private String subiect;
	private Byte citit;
	private Date data;

	public Mesaje() {
	}

	public Mesaje(String cnpSursa, String cnpDestinatie, String mesaj, String subiect, Byte citit, Date data) {
		this.cnpSursa = cnpSursa;
		this.cnpDestinatie = cnpDestinatie;
		this.mesaj = mesaj;
		this.subiect = subiect;
		this.citit = citit;
		this.data = data;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cnp_sursa", length = 45)
	public String getCnpSursa() {
		return this.cnpSursa;
	}

	public void setCnpSursa(String cnpSursa) {
		this.cnpSursa = cnpSursa;
	}

	@Column(name = "cnp_destinatie", length = 45)
	public String getCnpDestinatie() {
		return this.cnpDestinatie;
	}

	public void setCnpDestinatie(String cnpDestinatie) {
		this.cnpDestinatie = cnpDestinatie;
	}

	@Column(name = "mesaj", length = 500)
	public String getMesaj() {
		return this.mesaj;
	}

	public void setMesaj(String mesaj) {
		this.mesaj = mesaj;
	}

	@Column(name = "subiect", length = 45)
	public String getSubiect() {
		return this.subiect;
	}

	public void setSubiect(String subiect) {
		this.subiect = subiect;
	}

	@Column(name = "citit")
	public Byte getCitit() {
		return this.citit;
	}

	public void setCitit(Byte citit) {
		this.citit = citit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
