package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "Message", catalog = "MedicalEcoSystem")
public class Message implements java.io.Serializable {

	private Integer idMessage;
	private int sender;
	private int receiver;
	private String content;
	private Integer idReport;
	private String title;

	public Message() {
	}

	public Message(int sender, int receiver) {
		this.sender = sender;
		this.receiver = receiver;
	}

	public Message(int sender, int receiver, String content, Integer idReport, String title) {
		this.sender = sender;
		this.receiver = receiver;
		this.content = content;
		this.idReport = idReport;
		this.title = title;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMessage", unique = true, nullable = false)
	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	@Column(name = "sender", nullable = false)
	public int getSender() {
		return this.sender;
	}

	public void setSender(int sender) {
		this.sender = sender;
	}

	@Column(name = "receiver", nullable = false)
	public int getReceiver() {
		return this.receiver;
	}

	public void setReceiver(int receiver) {
		this.receiver = receiver;
	}

	@Column(name = "content", length = 100)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "idReport")
	public Integer getIdReport() {
		return this.idReport;
	}

	public void setIdReport(Integer idReport) {
		this.idReport = idReport;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
