package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OptiuniContract generated by hbm2java
 */
@Entity
@Table(name = "optiuni_contract", catalog = "MedicalEcoSystem")
public class OptiuniContract implements java.io.Serializable {

	private OptiuniContractId id;
	private Disciplina disciplina;
	private Utilizatori utilizatori;

	public OptiuniContract() {
	}

	public OptiuniContract(OptiuniContractId id, Disciplina disciplina, Utilizatori utilizatori) {
		this.id = id;
		this.disciplina = disciplina;
		this.utilizatori = utilizatori;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codDisciplina", column = @Column(name = "cod_disciplina", nullable = false)),
			@AttributeOverride(name = "cnpStudent", column = @Column(name = "cnp_student", nullable = false, length = 13)),
			@AttributeOverride(name = "anStudiu", column = @Column(name = "an_studiu", nullable = false)) })
	public OptiuniContractId getId() {
		return this.id;
	}

	public void setId(OptiuniContractId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_disciplina", nullable = false, insertable = false, updatable = false)
	public Disciplina getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(Disciplina disciplina) {
		this.disciplina = disciplina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cnp_student", nullable = false, insertable = false, updatable = false)
	public Utilizatori getUtilizatori() {
		return this.utilizatori;
	}

	public void setUtilizatori(Utilizatori utilizatori) {
		this.utilizatori = utilizatori;
	}

}
