package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OptiuniContractId generated by hbm2java
 */
@Embeddable
public class OptiuniContractId implements java.io.Serializable {

	private int codDisciplina;
	private String cnpStudent;
	private int anStudiu;

	public OptiuniContractId() {
	}

	public OptiuniContractId(int codDisciplina, String cnpStudent, int anStudiu) {
		this.codDisciplina = codDisciplina;
		this.cnpStudent = cnpStudent;
		this.anStudiu = anStudiu;
	}

	@Column(name = "cod_disciplina", nullable = false)
	public int getCodDisciplina() {
		return this.codDisciplina;
	}

	public void setCodDisciplina(int codDisciplina) {
		this.codDisciplina = codDisciplina;
	}

	@Column(name = "cnp_student", nullable = false, length = 13)
	public String getCnpStudent() {
		return this.cnpStudent;
	}

	public void setCnpStudent(String cnpStudent) {
		this.cnpStudent = cnpStudent;
	}

	@Column(name = "an_studiu", nullable = false)
	public int getAnStudiu() {
		return this.anStudiu;
	}

	public void setAnStudiu(int anStudiu) {
		this.anStudiu = anStudiu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OptiuniContractId))
			return false;
		OptiuniContractId castOther = (OptiuniContractId) other;

		return (this.getCodDisciplina() == castOther.getCodDisciplina())
				&& ((this.getCnpStudent() == castOther.getCnpStudent()) || (this.getCnpStudent() != null
						&& castOther.getCnpStudent() != null && this.getCnpStudent().equals(castOther.getCnpStudent())))
				&& (this.getAnStudiu() == castOther.getAnStudiu());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodDisciplina();
		result = 37 * result + (getCnpStudent() == null ? 0 : this.getCnpStudent().hashCode());
		result = 37 * result + this.getAnStudiu();
		return result;
	}

}
