package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orar generated by hbm2java
 */
@Entity
@Table(name = "orar", catalog = "MedicalEcoSystem")
public class Orar implements java.io.Serializable {

	private OrarId id;
	private Activitate activitate;
	private String zi;
	private int ora;
	private String sala;
	private int durata;
	private String frecventa;

	public Orar() {
	}

	public Orar(OrarId id, Activitate activitate, String zi, int ora, String sala, int durata, String frecventa) {
		this.id = id;
		this.activitate = activitate;
		this.zi = zi;
		this.ora = ora;
		this.sala = sala;
		this.durata = durata;
		this.frecventa = frecventa;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idActivitate", column = @Column(name = "id_activitate", nullable = false)),
			@AttributeOverride(name = "grupa", column = @Column(name = "grupa", nullable = false, length = 6)) })
	public OrarId getId() {
		return this.id;
	}

	public void setId(OrarId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_activitate", nullable = false, insertable = false, updatable = false)
	public Activitate getActivitate() {
		return this.activitate;
	}

	public void setActivitate(Activitate activitate) {
		this.activitate = activitate;
	}

	@Column(name = "zi", nullable = false, length = 10)
	public String getZi() {
		return this.zi;
	}

	public void setZi(String zi) {
		this.zi = zi;
	}

	@Column(name = "ora", nullable = false)
	public int getOra() {
		return this.ora;
	}

	public void setOra(int ora) {
		this.ora = ora;
	}

	@Column(name = "sala", nullable = false, length = 10)
	public String getSala() {
		return this.sala;
	}

	public void setSala(String sala) {
		this.sala = sala;
	}

	@Column(name = "durata", nullable = false)
	public int getDurata() {
		return this.durata;
	}

	public void setDurata(int durata) {
		this.durata = durata;
	}

	@Column(name = "frecventa", nullable = false, length = 15)
	public String getFrecventa() {
		return this.frecventa;
	}

	public void setFrecventa(String frecventa) {
		this.frecventa = frecventa;
	}

}
