package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pharmacytrans generated by hbm2java
 */
@Entity
@Table(name = "Pharmacytrans", catalog = "MedicalEcoSystem")
public class Pharmacytrans implements java.io.Serializable {

	private Integer idPharmacytrans;
	private String enterBy;
	private Date issueDate;
	private String custName;
	private String doctorName;
	private String qty;
	private String rate;
	private String amout;
	private int idUser;

	public Pharmacytrans() {
	}

	public Pharmacytrans(int idUser) {
		this.idUser = idUser;
	}

	public Pharmacytrans(String enterBy, Date issueDate, String custName, String doctorName, String qty, String rate,
			String amout, int idUser) {
		this.enterBy = enterBy;
		this.issueDate = issueDate;
		this.custName = custName;
		this.doctorName = doctorName;
		this.qty = qty;
		this.rate = rate;
		this.amout = amout;
		this.idUser = idUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPharmacytrans", unique = true, nullable = false)
	public Integer getIdPharmacytrans() {
		return this.idPharmacytrans;
	}

	public void setIdPharmacytrans(Integer idPharmacytrans) {
		this.idPharmacytrans = idPharmacytrans;
	}

	@Column(name = "enterBy", length = 45)
	public String getEnterBy() {
		return this.enterBy;
	}

	public void setEnterBy(String enterBy) {
		this.enterBy = enterBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "issueDate", length = 19)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "custName", length = 45)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "doctorName", length = 45)
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "qty", length = 45)
	public String getQty() {
		return this.qty;
	}

	public void setQty(String qty) {
		this.qty = qty;
	}

	@Column(name = "rate", length = 45)
	public String getRate() {
		return this.rate;
	}

	public void setRate(String rate) {
		this.rate = rate;
	}

	@Column(name = "amout", length = 45)
	public String getAmout() {
		return this.amout;
	}

	public void setAmout(String amout) {
		this.amout = amout;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

}
