package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Speciality generated by hbm2java
 */
@Entity
@Table(name = "Speciality", catalog = "MedicalEcoSystem", uniqueConstraints = { @UniqueConstraint(columnNames = "name"),
		@UniqueConstraint(columnNames = "Specialitycol") })
public class Speciality implements java.io.Serializable {

	private Integer idSpeciality;
	private String name;
	private String specialitycol;

	public Speciality() {
	}

	public Speciality(String name, String specialitycol) {
		this.name = name;
		this.specialitycol = specialitycol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSpeciality", unique = true, nullable = false)
	public Integer getIdSpeciality() {
		return this.idSpeciality;
	}

	public void setIdSpeciality(Integer idSpeciality) {
		this.idSpeciality = idSpeciality;
	}

	@Column(name = "name", unique = true, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Specialitycol", unique = true, length = 45)
	public String getSpecialitycol() {
		return this.specialitycol;
	}

	public void setSpecialitycol(String specialitycol) {
		this.specialitycol = specialitycol;
	}

}
