package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Study generated by hbm2java
 */
@Entity
@Table(name = "Study", catalog = "MedicalEcoSystem")
public class Study implements java.io.Serializable {

	private Integer idStudy;
	private Integer idReport;
	private int idUser;
	private String name;
	private String studyPhase;
	private String condition;
	private String intervention;
	private String officalTitle;
	private String sponseredBy;
	private String infoProvidedBy;
	private Date startDate;
	private Date endDate;
	private int idCatalog;
	private String studyType;
	private int idDrug;

	public Study() {
	}

	public Study(int idUser, int idCatalog, int idDrug) {
		this.idUser = idUser;
		this.idCatalog = idCatalog;
		this.idDrug = idDrug;
	}

	public Study(Integer idReport, int idUser, String name, String studyPhase, String condition, String intervention,
			String officalTitle, String sponseredBy, String infoProvidedBy, Date startDate, Date endDate, int idCatalog,
			String studyType, int idDrug) {
		this.idReport = idReport;
		this.idUser = idUser;
		this.name = name;
		this.studyPhase = studyPhase;
		this.condition = condition;
		this.intervention = intervention;
		this.officalTitle = officalTitle;
		this.sponseredBy = sponseredBy;
		this.infoProvidedBy = infoProvidedBy;
		this.startDate = startDate;
		this.endDate = endDate;
		this.idCatalog = idCatalog;
		this.studyType = studyType;
		this.idDrug = idDrug;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idStudy", unique = true, nullable = false)
	public Integer getIdStudy() {
		return this.idStudy;
	}

	public void setIdStudy(Integer idStudy) {
		this.idStudy = idStudy;
	}

	@Column(name = "idReport")
	public Integer getIdReport() {
		return this.idReport;
	}

	public void setIdReport(Integer idReport) {
		this.idReport = idReport;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "studyPhase", length = 7)
	public String getStudyPhase() {
		return this.studyPhase;
	}

	public void setStudyPhase(String studyPhase) {
		this.studyPhase = studyPhase;
	}

	@Column(name = "condition", length = 45)
	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	@Column(name = "intervention", length = 45)
	public String getIntervention() {
		return this.intervention;
	}

	public void setIntervention(String intervention) {
		this.intervention = intervention;
	}

	@Column(name = "officalTitle", length = 45)
	public String getOfficalTitle() {
		return this.officalTitle;
	}

	public void setOfficalTitle(String officalTitle) {
		this.officalTitle = officalTitle;
	}

	@Column(name = "sponseredBy", length = 45)
	public String getSponseredBy() {
		return this.sponseredBy;
	}

	public void setSponseredBy(String sponseredBy) {
		this.sponseredBy = sponseredBy;
	}

	@Column(name = "infoProvidedBy", length = 45)
	public String getInfoProvidedBy() {
		return this.infoProvidedBy;
	}

	public void setInfoProvidedBy(String infoProvidedBy) {
		this.infoProvidedBy = infoProvidedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startDate", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endDate", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "idCatalog", nullable = false)
	public int getIdCatalog() {
		return this.idCatalog;
	}

	public void setIdCatalog(int idCatalog) {
		this.idCatalog = idCatalog;
	}

	@Column(name = "studyType", length = 45)
	public String getStudyType() {
		return this.studyType;
	}

	public void setStudyType(String studyType) {
		this.studyType = studyType;
	}

	@Column(name = "idDrug", nullable = false)
	public int getIdDrug() {
		return this.idDrug;
	}

	public void setIdDrug(int idDrug) {
		this.idDrug = idDrug;
	}

}
