package neu.ying.entities;
// Generated Apr 7, 2017 12:12:31 PM by Hibernate Tools 5.0.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilizatori generated by hbm2java
 */
@Entity
@Table(name = "utilizatori", catalog = "MedicalEcoSystem")
public class Utilizatori implements java.io.Serializable {

	private String cnp;
	private String parola;
	private String tip;
	private String nume;
	private String prenume;
	private String email;
	private String adresa;
	private String titluGrupa;
	private String finantare;
	private Boolean contractCompletat;
	private String taxa;
	private Set optiuniContracts = new HashSet(0);
	private Set activitates = new HashSet(0);
	private Set catalogs = new HashSet(0);

	public Utilizatori() {
	}

	public Utilizatori(String cnp, String parola, String tip, String nume, String prenume) {
		this.cnp = cnp;
		this.parola = parola;
		this.tip = tip;
		this.nume = nume;
		this.prenume = prenume;
	}

	public Utilizatori(String cnp, String parola, String tip, String nume, String prenume, String email, String adresa,
			String titluGrupa, String finantare, Boolean contractCompletat, String taxa, Set optiuniContracts,
			Set activitates, Set catalogs) {
		this.cnp = cnp;
		this.parola = parola;
		this.tip = tip;
		this.nume = nume;
		this.prenume = prenume;
		this.email = email;
		this.adresa = adresa;
		this.titluGrupa = titluGrupa;
		this.finantare = finantare;
		this.contractCompletat = contractCompletat;
		this.taxa = taxa;
		this.optiuniContracts = optiuniContracts;
		this.activitates = activitates;
		this.catalogs = catalogs;
	}

	@Id

	@Column(name = "cnp", unique = true, nullable = false, length = 13)
	public String getCnp() {
		return this.cnp;
	}

	public void setCnp(String cnp) {
		this.cnp = cnp;
	}

	@Column(name = "parola", nullable = false, length = 25)
	public String getParola() {
		return this.parola;
	}

	public void setParola(String parola) {
		this.parola = parola;
	}

	@Column(name = "tip", nullable = false, length = 15)
	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	@Column(name = "nume", nullable = false, length = 45)
	public String getNume() {
		return this.nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	@Column(name = "prenume", nullable = false, length = 45)
	public String getPrenume() {
		return this.prenume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "adresa", length = 120)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "titlu_grupa", length = 15)
	public String getTitluGrupa() {
		return this.titluGrupa;
	}

	public void setTitluGrupa(String titluGrupa) {
		this.titluGrupa = titluGrupa;
	}

	@Column(name = "finantare", length = 10)
	public String getFinantare() {
		return this.finantare;
	}

	public void setFinantare(String finantare) {
		this.finantare = finantare;
	}

	@Column(name = "contract_completat")
	public Boolean getContractCompletat() {
		return this.contractCompletat;
	}

	public void setContractCompletat(Boolean contractCompletat) {
		this.contractCompletat = contractCompletat;
	}

	@Column(name = "taxa", length = 20)
	public String getTaxa() {
		return this.taxa;
	}

	public void setTaxa(String taxa) {
		this.taxa = taxa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilizatori")
	public Set getOptiuniContracts() {
		return this.optiuniContracts;
	}

	public void setOptiuniContracts(Set optiuniContracts) {
		this.optiuniContracts = optiuniContracts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilizatori")
	public Set getActivitates() {
		return this.activitates;
	}

	public void setActivitates(Set activitates) {
		this.activitates = activitates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilizatori")
	public Set getCatalogs() {
		return this.catalogs;
	}

	public void setCatalogs(Set catalogs) {
		this.catalogs = catalogs;
	}

}
